spring.application.name=ticketeer
#server.port=8090
server.port=@server.port@

#Database Configurations
#podman run -idt --name postgres-ticketeer -p 5432:5432 -e POSTGRES_USER=ticketeer_db -e POSTGRES_PASSWORD=ticketeer -e POSTGRES_DB=ticketeer_main postgres:15.15-trixie
#spring.datasource.url=jdbc:postgresql://192.168.0.196:5432/ticketeer_main
spring.datasource.url=@db.url@
spring.datasource.username=@db.username@
spring.datasource.password=@db.password@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=@db.schema.management@
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect