spring.application.name=ticketeer-customer
server.port=8091

#RabbitMQ Configurations
spring.rabbitmq.host=@spring.rabbitmq.host@
spring.rabbitmq.port=@spring.rabbitmq.port@
spring.rabbitmq.username=@rabbitmq.username@
spring.rabbitmq.password=@rabbitmq.password@

rabbitmq.queue=@rabbitmq.queue@
rabbitmq.exchange=@rabbitmq.exchange@
rabbitmq.routing.key=@rabbitmq.routing.key@