spring.application.name=ticketeer-purchases-worker

spring.rabbitmq.host=@mq.host@
spring.rabbitmq.port=@mq.port@
spring.rabbitmq.username=@mq.username@
spring.rabbitmq.password=@mq.password@

spring.datasource.url=@db.url@
spring.datasource.username=@db.username@
spring.datasource.password=@db.password@
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=@db.schema.management@
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

queue.message.retry.limit=@mq.retry.limit@

rabbitmq.dlq.exchange=@mq.dlq.exchange@
rabbitmq.dlq.routing.key=@mq.dlq.routing.key@