spring.application.name=ticketeer-purchases-worker

#spring.rabbitmq.host=192.168.1.10
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=rabbitmq_user
spring.rabbitmq.password=1234

spring.datasource.url=jdbc:postgresql://localhost:5432/ticketeer_main
spring.datasource.username=ticketeer_db
spring.datasource.password=ticketeer
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

queue.message.retry.limit=3

rabbitmq.dlq.exchange=purchases.dlq.exchange
rabbitmq.dlq.routing.key=ticketeer.purchases.dlq
#rabbitmq.dlq=purchases.dlq
